SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `name_test`;
CREATE TABLE `name_test` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `sub` varchar(255) CHARACTER SET utf8 DEFAULT '',
  `update_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=30 DEFAULT CHARSET=latin1;